Business Problem

In this project we will try to find an optimal location for a restaurant. Specifically, this report will be targeted to stakeholders interested in opening an **Fast Food restaurant** in **chicago**, usa.
Here I used Chicago Public Schools progress Report cards 2011-2012 dataset for this project 
Used **Four Square API** to find the latitude & longitude of Chicago city center

In [108]:
#Importing Libraries
import numpy as np 
import pandas as pd 
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

import json 


from geopy.geocoders import Nominatim 

import requests 
from pandas.io.json import json_normalize 

import matplotlib.cm as cm
import matplotlib.colors as colors


from sklearn.cluster import KMeans


import folium 

print('Libraries imported.')

Libraries imported.

In [109]:
df = pd.read_csv(r'C:\Users\Sushma\Downloads\Chicago_Public_Schools.csv')

In [110]:
df = pd.read_csv(r'C:\Users\Sushma\Downloads\Chicago_Public_Schools.csv')
df['Address'] = df[df.columns[2:6]].apply(lambda x: ','.join(x.dropna().astype(str)), axis=1)
finaldf=df.append(df['Address'])
finaldf=finaldf[['School Name','Address','Latitude','Longitude','COMMUNITY_AREA_NAME']]
#finaldf=finaldf.rename(columns={'columns names':'columns names','columns names':'columns names'})
finaldf=finaldf.iloc[0:100,:]
finaldf

,School Name,Address,Latitude,Longitude,COMMUNITY_AREA_NAME
0,Abraham Lincoln Elementary School,"ES,615 W Kemper Pl ,Chicago,IL",41.924497,-87.644522,LINCOLN PARK
1,Adam Clayton Powell Paideia Community Academy ...,"ES,7511 S South Shore Dr ,Chicago,IL",41.760324,-87.556736,SOUTH SHORE
2,Adlai E Stevenson Elementary School,"ES,8010 S Kostner Ave ,Chicago,IL",41.747111,-87.731702,ASHBURN
3,Agustin Lara Elementary Academy,"ES,4619 S Wolcott Ave ,Chicago,IL",41.809757,-87.672145,NEW CITY
4,Air Force Academy High School,"HS,3630 S Wells St ,Chicago,IL",41.828146,-87.632794,ARMOUR SQUARE
5,Albany Park Multicultural Academy,"MS,4929 N Sawyer Ave ,Chicago,IL",41.971143,-87.709627,ALBANY PARK
6,Albert G Lane Technical High School,"HS,2501 W Addison St ,Chicago,IL",41.946617,-87.691056,NORTH CENTER
7,Albert R Sabin Elementary Magnet School,"ES,2216 W Hirsch St ,Chicago,IL",41.906843,-87.683043,WEST TOWN
8,Alcott High School for the Humanities,"HS,2957 N Hoyne Ave ,Chicago,IL",41.935761,-87.680524,NORTH CENTER
9,Alessandro Volta Elementary School,"ES,4950 N Avers Ave ,Chicago,IL",41.971606,-87.724641,ALBANY PARK
10,Alexander Graham Bell Elementary School,"ES,3730 N Oakley Ave ,Chicago,IL",41.949528,-87.686055,NORTH CENTER
11,Alexander Graham Elementary School,"ES,4436 S Union Ave ,Chicago,IL",41.813292,-87.643381,NEW CITY
12,Alexander Hamilton Elementary School,"ES,1650 W Cornelia Ave ,Chicago,IL",41.945247,-87.670857,LAKE VIEW
13,Alexander von Humboldt Elementary School,"ES,2620 W Hirsch St ,Chicago,IL",41.906722,-87.693003,WEST TOWN
14,Alex Haley Elementary Academy,"ES,11411 S Eggleston Ave ,Chicago,IL",41.686637,-87.633595,ROSELAND
15,Alfred David Kohn Elementary School,"ES,10414 S State St ,Chicago,IL",41.704851,-87.623602,ROSELAND
16,Alfred Nobel Elementary School,"ES,4127 W Hirsch St ,Chicago,IL",41.906128,-87.729933,HUMBOLDT PARK
17,Alice L Barnard Computer Math & Science Center...,"ES,10354 S Charles St ,Chicago,IL",41.705140,-87.658116,BEVERLY
18,Al Raby High School,"HS,3545 W Fulton Blvd ,Chicago,IL",41.886183,-87.715397,EAST GARFIELD PARK
19,Ambrose Plamondon Elementary School,"ES,2642 W 15th Pl ,Chicago,IL",41.860287,-87.692505,NORTH LAWNDALE
20,Amelia Earhart Options for Knowledge Elementar...,"ES,1710 E 93rd St ,Chicago,IL",41.726135,-87.582177,CALUMET HEIGHTS
21,Ames Middle School,"MS,1920 N Hamlin Ave ,Chicago,IL",41.916055,-87.721779,LOGAN SQUARE
22,Amos Alonzo Stagg Elementary School,"ES,7424 S Morgan St ,Chicago,IL",41.758927,-87.649253,ENGLEWOOD
23,Ana Roque de Duprey Elementary School,"ES,2620 W Hirsch St ,Chicago,IL",41.906722,-87.693003,WEST TOWN
24,Andrew Carnegie Elementary School,"ES,1414 E 61st Pl ,Chicago,IL",41.783396,-87.590796,WOODLAWN
25,Andrew Jackson Elementary Language Academy,"ES,1340 W Harrison St ,Chicago,IL",41.874327,-87.660976,NEAR WEST SIDE
26,Anna R. Langford Community Academy,"ES,6010 S Throop St ,Chicago,IL",41.784657,-87.657205,WEST ENGLEWOOD
27,Annie Keller Elementary Gifted Magnet School,"ES,3020 W 108th St ,Chicago,IL",41.697198,-87.697264,MOUNT GREENWOOD
28,A.N. Pritzker School,"ES,2009 W Schiller St ,Chicago,IL",41.907025,-87.677796,WEST TOWN
29,Anthony Overton Elementary School,"ES,221 E 49th St ,Chicago,IL",41.805576,-87.620123,GRAND BOULEVARD
30,Ariel Elementary Community Academy,"ES,1119 E 46th St ,Chicago,IL",41.811334,-87.598500,KENWOOD
31,Arna Wendell Bontemps Elementary School,"ES,1241 W 58th St ,Chicago,IL",41.788573,-87.656345,WEST ENGLEWOOD
32,Arnold Mireles Elementary Academy,"ES,9000 S Exchange Ave ,Chicago,IL",41.731682,-87.552824,SOUTH CHICAGO
33,Arthur A Libby Elementary School,"ES,5300 S Loomis Blvd ,Chicago,IL",41.797648,-87.659969,NEW CITY
34,Arthur Dixon Elementary School,"ES,8306 S Saint Lawrence Ave ,Chicago,IL",41.743658,-87.610015,CHATHAM
35,Arthur E Canty Elementary School,"ES,3740 N Panama Ave ,Chicago,IL",41.947992,-87.829332,DUNNING
36,Arthur R Ashe Elementary School,"ES,8505 S Ingleside Ave ,Chicago,IL",41.740153,-87.601137,CHATHAM
37,Asa Philip Randolph Elementary School,"ES,7316 S Hoyne Ave ,Chicago,IL",41.760597,-87.676002,WEST ENGLEWOOD
38,Ashburn Community Elementary School,"ES,8300 S Saint Louis Ave ,Chicago,IL",41.742332,-87.709646,ASHBURN
39,Augustus H Burley Elementary School,"ES,1630 W Barry Ave ,Chicago,IL",41.937965,-87.669852,LAKE VIEW
40,Austin Business and Entrepreneurship Academy H...,"HS,231 N Pine Ave ,Chicago,IL",41.885205,-87.763212,AUSTIN
41,Austin O Sexton Elementary School,"ES,6020 S Langley Ave ,Chicago,IL",41.785171,-87.608669,WOODLAWN
42,Austin Polytechnical Academy High School,"HS,231 N Pine Ave ,Chicago,IL",41.885205,-87.763212,AUSTIN
43,Avalon Park Elementary School,"ES,8045 S Kenwood Ave ,Chicago,IL",41.748266,-87.591618,AVALON PARK
44,Barbara Vick Early Childhood & Family Center,"ES,2554 W 113th St ,Chicago,IL",41.688218,-87.685663,MORGAN PARK
45,Belmont-Cragin Elementary School,"ES,2456 N Mango Ave ,Chicago,IL",41.925596,-87.769843,BELMONT CRAGIN
46,Benito Juarez Community Academy High School,"HS,2150 S Laflin St ,Chicago,IL",41.852673,-87.663769,LOWER WEST SIDE
47,Benjamin Banneker Elementary School,"ES,6656 S Normal Blvd ,Chicago,IL",41.772754,-87.637295,ENGLEWOOD
48,Benjamin E Mays Elementary Academy,"ES,838 W Marquette Rd ,Chicago,IL",41.772561,-87.646127,ENGLEWOOD
49,Bernhard Moos Elementary School,"ES,1711 N California Ave ,Chicago,IL",41.912531,-87.696905,WEST TOWN
50,Betsy Ross Elementary School,"ES,6059 S Wabash Ave ,Chicago,IL",41.783834,-87.623654,WASHINGTON PARK
51,Beulah Shoesmith Elementary School,"ES,1330 E 50th St ,Chicago,IL",41.804321,-87.593922,KENWOOD
52,Blair Early Childhood Center,"ES,6751 W 63rd Pl ,Chicago,IL",41.776529,-87.790568,CLEARING
53,Bret Harte Elementary School,"ES,1556 E 56th St ,Chicago,IL",41.793475,-87.586863,HYDE PARK
54,Brian Piccolo Elementary Specialty School,"ES,1040 N Keeler Ave ,Chicago,IL",41.900146,-87.731298,HUMBOLDT PARK
55,Brighton Park Elementary School,"ES,3825 S Washtenaw Ave ,Chicago,IL",41.823914,-87.692041,BRIGHTON PARK
56,Bronzeville Scholastic Academy High School,"HS,4934 S Wabash Ave ,Chicago,IL",41.804564,-87.624484,GRAND BOULEVARD
57,Burnham Elementary Inclusive Academy,"ES,1903 E 96th St ,Chicago,IL",41.720502,-87.577595,SOUTH DEERING
58,Burnside Elementary Scholastic Academy,"ES,650 E 91st Pl ,Chicago,IL",41.728508,-87.607471,CHATHAM
59,Calmeca Academy of Fine Arts and Dual Language,"ES,3456 W 38th St ,Chicago,IL",41.824405,-87.711609,BRIGHTON PARK
60,Carl Schurz High School,"HS,3601 N Milwaukee Ave ,Chicago,IL",41.946408,-87.735625,IRVING PARK
61,Carl von Linne Elementary School,"ES,3221 N Sacramento Ave ,Chicago,IL",41.940019,-87.702598,AVONDALE
62,Carrie Jacobs Bond Elementary School,"ES,7050 S May St ,Chicago,IL",41.765386,-87.653055,ENGLEWOOD
63,Carroll-Rosenwald Specialty Elementary School,"ES,2929 W 83rd St ,Chicago,IL",41.742489,-87.696003,ASHBURN
64,Carter G Woodson South Elementary School,"ES,4414 S Evans ,Chicago,IL",41.814480,-87.608455,GRAND BOULEVARD
65,Cesar E Chavez Multicultural Academic Center E...,"ES,4747 S Marshfield Ave ,Chicago,IL",41.807155,-87.666001,NEW CITY
66,Charles Allen Prosser Career Academy High School,"HS,2148 N Long Ave ,Chicago,IL",41.920036,-87.761084,BELMONT CRAGIN
67,Charles Evans Hughes Elementary School,"ES,4247 W 15th St ,Chicago,IL",41.860490,-87.731775,NORTH LAWNDALE
68,Charles Gates Dawes Elementary School,"ES,3810 W 81st Pl ,Chicago,IL",41.745105,-87.717386,ASHBURN
69,Charles G Hammond Elementary School,"ES,2819 W 21st Pl ,Chicago,IL",41.852691,-87.696278,SOUTH LAWNDALE
70,Charles H Wacker Elementary School,"ES,9746 S Morgan St ,Chicago,IL",41.716215,-87.648081,WASHINGTON HEIGHTS
71,Charles Kozminski Elementary Community Academy,"ES,936 E 54th St ,Chicago,IL",41.798029,-87.602463,HYDE PARK
72,Charles N Holden Elementary School,"ES,1104 W 31st St ,Chicago,IL",41.838055,-87.653800,BRIDGEPORT
73,Charles P Caldwell Academy of Math & Science E...,"ES,8546 S Cregier ,Chicago,IL",41.739227,-87.580766,AVALON PARK
74,Charles P Steinmetz Academic Centre High School,"HS,3030 N Mobile Ave ,Chicago,IL",41.935632,-87.783552,BELMONT CRAGIN
75,Charles R Darwin Elementary School,"ES,3116 W Belden Ave ,Chicago,IL",41.923350,-87.705431,LOGAN SQUARE
76,Charles R Henderson Elementary School,"ES,5650 S Wolcott Ave ,Chicago,IL",41.790617,-87.671925,WEST ENGLEWOOD
77,Charles S Brownell Elementary School,"ES,6741 S Michigan Ave ,Chicago,IL",41.771635,-87.621710,GREATER GRAND CROSSING
78,Charles S Deneen Elementary School,"ES,7240 S Wabash Ave ,Chicago,IL",41.762504,-87.623382,GREATER GRAND CROSSING
79,Charles Sumner Math & Science Community Acad ...,"ES,4320 W 5th Ave ,Chicago,IL",41.870849,-87.733554,WEST GARFIELD PARK
80,Charles W Earle Elementary School,"ES,6121 S Hermitage Ave ,Chicago,IL",41.782302,-87.667777,WEST ENGLEWOOD
81,Chicago Academy Elementary School,"ES,3400 N Austin Ave ,Chicago,IL",41.942154,-87.776506,DUNNING
82,Chicago Academy High School,"HS,3400 N Austin Ave ,Chicago,IL",41.942154,-87.776506,DUNNING
83,Chicago High School for Agricultural Sciences,"HS,3857 W 111th St ,Chicago,IL",41.691194,-87.717739,MOUNT GREENWOOD
84,Chicago Military Academy High School,"HS,3519 S Giles Ave ,Chicago,IL",41.830538,-87.619178,DOUGLAS
85,Chicago Vocational Career Academy High School,"HS,2100 E 87th St ,Chicago,IL",41.737202,-87.573244,AVALON PARK
86,Christian Ebinger Elementary School,"ES,7350 W Pratt Ave ,Chicago,IL",42.004436,-87.811164,EDISON PARK
87,Christian Fenger Academy High School,"HS,11220 S Wallace St ,Chicago,IL",41.689939,-87.637608,ROSELAND
88,Christopher Columbus Elementary School,"ES,1003 N Leavitt St ,Chicago,IL",41.899581,-87.681902,WEST TOWN
89,Clara Barton Elementary School,"ES,7650 S Wolcott Ave ,Chicago,IL",41.754220,-87.670965,AUBURN GRESHAM
90,Claremont Academy Elementary School,"ES,2300 W 64th St ,Chicago,IL",41.777538,-87.681086,CHICAGO LAWN
91,Collins Academy High School,"HS,1313 S Sacramento Dr ,Chicago,IL",41.864162,-87.702008,NORTH LAWNDALE
92,Columbia Explorers Elementary Academy,"ES,4520 S Kedzie Ave ,Chicago,IL",41.811057,-87.704235,BRIGHTON PARK
93,Countee Cullen Elementary School,"ES,10650 S Eberhart Ave ,Chicago,IL",41.700361,-87.611282,ROSELAND
94,Crispus Attucks Elementary School,"ES,5055 S State St ,Chicago,IL",41.802143,-87.625747,GRAND BOULEVARD
95,Crown Community Academy of Fine Arts Center El...,"ES,2128 S Saint Louis Ave ,Chicago,IL",41.852662,-87.712507,NORTH LAWNDALE
96,Cyrus H McCormick Elementary School,"ES,2712 S Sawyer Ave ,Chicago,IL",41.842245,-87.706336,SOUTH LAWNDALE
97,Daniel Boone Elementary School,"ES,6710 N Washtenaw Ave ,Chicago,IL",42.003435,-87.697500,WEST RIDGE
98,Daniel C Beard Elementary School,"ES,6445 W Strong St ,Chicago,IL",41.970097,-87.789637,NORWOOD PARK
99,Daniel Hale Williams Prep School of Medicine,"HS,4934 S Wabash Ave ,Chicago,IL",41.804564,-87.624484,GRAND BOULEVARD

In [112]:
df.loc[df.COMMUNITY_AREA_NAME=='NEW CITY'].Address

3         ES,4619 S Wolcott Ave ,Chicago,IL
11          ES,4436 S Union Ave ,Chicago,IL
33        ES,5300 S Loomis Blvd ,Chicago,IL
65     ES,4747 S Marshfield Ave ,Chicago,IL
106         ES,5415 S Union Ave ,Chicago,IL
130         HS,4747 S Union Ave ,Chicago,IL
140         HS,5009 S Laflin St ,Chicago,IL
246    ES,4747 S Winchester Ave ,Chicago,IL
283         ES,4747 S Bishop St ,Chicago,IL
449       ES,5024 S Wolcott Ave ,Chicago,IL
456     ES,5300 S Hermitage Ave ,Chicago,IL
549     ES,4600 S Hermitage Ave ,Chicago,IL
561           ES,1000 W 52nd St ,Chicago,IL
Name: Address, dtype: object

In [179]:
CLIENT_ID = '                                         ' #  Foursquare ID
CLIENT_SECRET = '                                 ' #  Foursquare Secret
VERSION = '20180604'
LIMIT = 30
print('Your credentails:')
print('CLIENT_ID: ' + CLIENT_ID)
print('CLIENT_SECRET:' + CLIENT_SECRET)
print ('printed credentials')

printed credentials

In [99]:
address = '4619 S Wolcott Ave, Chicago IL'

geolocator = Nominatim(user_agent="foursquare_agent")
location = geolocator.geocode(address)
latitude = location.latitude
longitude = location.longitude
print(latitude, longitude)

41.80972665 -87.671915249027

In [93]:
search_query = 'Italian '
radius = 500
print(search_query + ' .... OK!')

italian  .... OK!

In [ ]:
url = 'https://api.foursquare.com/v2/venues/search?client_id={}&client_secret={}&ll={},{}&v={}&query={}&radius={}&limit={}'.format(
    CLIENT_ID, 
    CLIENT_SECRET, 
    latitude, 
    longitude, 
    VERSION, 
    search_query, 
    radius, 
    LIMIT)
url

The above cell has Foursquare Crendtials

In [9]:
results = requests.get(url).json()
results

{'meta': {'code': 200, 'requestId': '5caec0d31ed2190befc726e3'},
 'response': {'venues': [{'id': '533c4dae498e7a99cdeb21cd',
    'name': 'tacos guerrero 1922 w. 47th',
    'location': {'lat': 41.80872,
     'lng': -87.673196,
     'labeledLatLngs': [{'label': 'display',
       'lat': 41.80872,
       'lng': -87.673196}],
     'distance': 154,
     'cc': 'US',
     'city': 'Chicago',
     'state': 'IL',
     'country': 'United States',
     'formattedAddress': ['Chicago, IL', 'United States']},
    'categories': [{'id': '4bf58dd8d48988d1c1941735',
      'name': 'Mexican Restaurant',
      'pluralName': 'Mexican Restaurants',
      'shortName': 'Mexican',
      'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/mexican_',
       'suffix': '.png'},
      'primary': True}],
    'referralId': 'v-1554956499',
    'hasPerk': False},
   {'id': '4e9b6529f790b2a919af0218',
    'name': 'Don Cucos Tacos',
    'location': {'address': '1847 W 47th St',
     'lat': 41.808645,
     'lng': -87.671684,
     'labeledLatLngs': [{'label': 'display',
       'lat': 41.808645,
       'lng': -87.671684}],
     'distance': 121,
     'postalCode': '60609',
     'cc': 'US',
     'city': 'Chicago',
     'state': 'IL',
     'country': 'United States',
     'formattedAddress': ['1847 W 47th St',
      'Chicago, IL 60609',
      'United States']},
    'categories': [{'id': '4bf58dd8d48988d1c1941735',
      'name': 'Mexican Restaurant',
      'pluralName': 'Mexican Restaurants',
      'shortName': 'Mexican',
      'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/mexican_',
       'suffix': '.png'},
      'primary': True}],
    'referralId': 'v-1554956499',
    'hasPerk': False},
   {'id': '4d866d4b99b78cfa8b7ee41f',
    'name': 'Bella Fuentes',
    'location': {'lat': 41.808540135294905,
     'lng': -87.66853747260767,
     'labeledLatLngs': [{'label': 'display',
       'lat': 41.808540135294905,
       'lng': -87.66853747260767}],
     'distance': 309,
     'cc': 'US',
     'state': 'Illinois',
     'country': 'United States',
     'formattedAddress': ['Illinois', 'United States']},
    'categories': [{'id': '4bf58dd8d48988d1c1941735',
      'name': 'Mexican Restaurant',
      'pluralName': 'Mexican Restaurants',
      'shortName': 'Mexican',
      'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/mexican_',
       'suffix': '.png'},
      'primary': True}],
    'referralId': 'v-1554956499',
    'hasPerk': False}]}}

In [10]:
venues = results['response']['venues']

# tranform venues into a dataframe
dataframe = json_normalize(venues)
dataframe.head()

,categories,hasPerk,id,location.address,location.cc,location.city,location.country,location.distance,location.formattedAddress,location.labeledLatLngs,location.lat,location.lng,location.postalCode,location.state,name,referralId
0,"[{'id': '4bf58dd8d48988d1c1941735', 'name': 'M...",False,533c4dae498e7a99cdeb21cd,NaN,US,Chicago,United States,154,"[Chicago, IL, United States]","[{'label': 'display', 'lat': 41.80872, 'lng': ...",41.808720,-87.673196,NaN,IL,tacos guerrero 1922 w. 47th,v-1554956499
1,"[{'id': '4bf58dd8d48988d1c1941735', 'name': 'M...",False,4e9b6529f790b2a919af0218,1847 W 47th St,US,Chicago,United States,121,"[1847 W 47th St, Chicago, IL 60609, United Sta...","[{'label': 'display', 'lat': 41.808645, 'lng':...",41.808645,-87.671684,60609,IL,Don Cucos Tacos,v-1554956499
2,"[{'id': '4bf58dd8d48988d1c1941735', 'name': 'M...",False,4d866d4b99b78cfa8b7ee41f,NaN,US,NaN,United States,309,"[Illinois, United States]","[{'label': 'display', 'lat': 41.80854013529490...",41.808540,-87.668537,NaN,Illinois,Bella Fuentes,v-1554956499

In [11]:
filtered_columns = ['name', 'categories'] + [col for col in dataframe.columns if col.startswith('location.')] + ['id']
dataframe_filtered = dataframe.loc[:, filtered_columns]

# function that extracts the category of the venue
def get_category_type(row):
    try:
        categories_list = row['categories']
    except:
        categories_list = row['venue.categories']
        
    if len(categories_list) == 0:
        return None
    else:
        return categories_list[0]['name']

# filter the category for each row
dataframe_filtered['categories'] = dataframe_filtered.apply(get_category_type, axis=1)

# column names by keeping only last term
dataframe_filtered.columns = [column.split('.')[-1] for column in dataframe_filtered.columns]

dataframe_filtered

,name,categories,address,cc,city,country,distance,formattedAddress,labeledLatLngs,lat,lng,postalCode,state,id
0,tacos guerrero 1922 w. 47th,Mexican Restaurant,NaN,US,Chicago,United States,154,"[Chicago, IL, United States]","[{'label': 'display', 'lat': 41.80872, 'lng': ...",41.808720,-87.673196,NaN,IL,533c4dae498e7a99cdeb21cd
1,Don Cucos Tacos,Mexican Restaurant,1847 W 47th St,US,Chicago,United States,121,"[1847 W 47th St, Chicago, IL 60609, United Sta...","[{'label': 'display', 'lat': 41.808645, 'lng':...",41.808645,-87.671684,60609,IL,4e9b6529f790b2a919af0218
2,Bella Fuentes,Mexican Restaurant,NaN,US,NaN,United States,309,"[Illinois, United States]","[{'label': 'display', 'lat': 41.80854013529490...",41.808540,-87.668537,NaN,Illinois,4d866d4b99b78cfa8b7ee41f

In [12]:
dataframe_filtered.name

0    tacos guerrero 1922 w. 47th
1                Don Cucos Tacos
2                  Bella Fuentes
Name: name, dtype: object

In [48]:
venues_map = folium.Map(location=[latitude, longitude], zoom_start=13) 


folium.features.CircleMarker(
    [latitude, longitude],
    radius=10,
    color='red',
    popup='Conrad Hotel',
    fill = True,
    fill_color = 'red',
    fill_opacity = 0.6
).add_to(venues_map)


for lat, lng, label in zip(dataframe_filtered.lat, dataframe_filtered.lng, dataframe_filtered.categories):
    folium.features.CircleMarker(
        [lat, lng],
        radius=5,
        color='blue',
        popup=label,
        fill = True,
        fill_color='blue',
        fill_opacity=0.6
    ).add_to(venues_map)

# display map
venues_map

In [146]:
address = '  302 S Wells St, Chicago, Chicago IL'

geolocator = Nominatim(user_agent="foursquare_agent")
location = geolocator.geocode(address)
latitude = location.latitude
longitude = location.longitude
print(latitude, longitude)

41.8779731447148 -87.6338343631974

In [147]:
search_query = 'Pizza'
radius = 500
print(search_query + ' .... OK!')

Pizza .... OK!

In [148]:
results = requests.get(url).json()
results

{'meta': {'code': 200, 'requestId': '5cb0ea266a60715add87c723'},
 'response': {'venues': [{'id': '4ae0ca21f964a520838221e3',
    'name': "Uncle Julio's Hacienda",
    'location': {'address': '855 W North Ave',
     'crossStreet': 'at N Clybourn Ave',
     'lat': 41.9107157127916,
     'lng': -87.65045095940448,
     'labeledLatLngs': [{'label': 'display',
       'lat': 41.9107157127916,
       'lng': -87.65045095940448}],
     'distance': 11,
     'postalCode': '60642',
     'cc': 'US',
     'city': 'Chicago',
     'state': 'IL',
     'country': 'United States',
     'formattedAddress': ['855 W North Ave (at N Clybourn Ave)',
      'Chicago, IL 60642',
      'United States']},
    'categories': [{'id': '4bf58dd8d48988d1c1941735',
      'name': 'Mexican Restaurant',
      'pluralName': 'Mexican Restaurants',
      'shortName': 'Mexican',
      'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/mexican_',
       'suffix': '.png'},
      'primary': True}],
    'referralId': 'v-1555098150',
    'hasPerk': False}]}}

In [149]:
venues = results['response']['venues']

# tranform venues into a dataframe
dataframe = json_normalize(venues)
dataframe.head()

,categories,hasPerk,id,location.address,location.cc,location.city,location.country,location.crossStreet,location.distance,location.formattedAddress,location.labeledLatLngs,location.lat,location.lng,location.postalCode,location.state,name,referralId
0,"[{'id': '4bf58dd8d48988d1c1941735', 'name': 'M...",False,4ae0ca21f964a520838221e3,855 W North Ave,US,Chicago,United States,at N Clybourn Ave,11,"[855 W North Ave (at N Clybourn Ave), Chicago,...","[{'label': 'display', 'lat': 41.9107157127916,...",41.910716,-87.650451,60642,IL,Uncle Julio's Hacienda,v-1555098150

In [150]:

filtered_columns = ['name', 'categories'] + [col for col in dataframe.columns if col.startswith('location.')] + ['id']
dataframe_filtered = dataframe.loc[:, filtered_columns]


def get_category_type(row):
    try:
        categories_list = row['categories']
    except:
        categories_list = row['venue.categories']
        
    if len(categories_list) == 0:
        return None
    else:
        return categories_list[0]['name']


dataframe_filtered['categories'] = dataframe_filtered.apply(get_category_type, axis=1)

#  column names by keeping only last term
dataframe_filtered.columns = [column.split('.')[-1] for column in dataframe_filtered.columns]

dataframe_filtered

,name,categories,address,cc,city,country,crossStreet,distance,formattedAddress,labeledLatLngs,lat,lng,postalCode,state,id
0,Uncle Julio's Hacienda,Mexican Restaurant,855 W North Ave,US,Chicago,United States,at N Clybourn Ave,11,"[855 W North Ave (at N Clybourn Ave), Chicago,...","[{'label': 'display', 'lat': 41.9107157127916,...",41.910716,-87.650451,60642,IL,4ae0ca21f964a520838221e3

In [151]:
dataframe_filtered.name

0    Uncle Julio's Hacienda
Name: name, dtype: object

In [25]:
address = ' 4619 S Wolcott Ave, Chicago IL'

geolocator = Nominatim(user_agent="foursquare_agent")
location = geolocator.geocode(address)
latitude = location.latitude
longitude = location.longitude
print(latitude, longitude)

41.80972665 -87.671915249027

In [26]:
search_query = 'Sub Way '
radius = 500
print(search_query + ' .... OK!')

Sub Way  .... OK!

In [ ]:
url = 'https://api.foursquare.com/v2/venues/search?client_id={}&client_secret={}&ll={},{}&v={}&query={}&radius={}&limit={}'.format(
    CLIENT_ID, 
    CLIENT_SECRET, 
    latitude, 
    longitude, 
    VERSION, 
    search_query, 
    radius, 
    LIMIT)
url

The above cell has foursquare credentials

In [28]:
results = requests.get(url).json()
results

{'meta': {'code': 200, 'requestId': '5caed3c66a60712cf4203bb5'},
 'response': {'venues': [{'id': '4c378c483849c92809e8bdb1',
    'name': 'Subway',
    'location': {'address': '4606 S Damen Ave',
     'lat': 41.80994293842322,
     'lng': -87.67683391497275,
     'labeledLatLngs': [{'label': 'display',
       'lat': 41.80994293842322,
       'lng': -87.67683391497275}],
     'distance': 408,
     'postalCode': '60609',
     'cc': 'US',
     'city': 'Chicago',
     'state': 'IL',
     'country': 'United States',
     'formattedAddress': ['4606 S Damen Ave',
      'Chicago, IL 60609',
      'United States']},
    'categories': [{'id': '4bf58dd8d48988d1c5941735',
      'name': 'Sandwich Place',
      'pluralName': 'Sandwich Places',
      'shortName': 'Sandwiches',
      'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/deli_',
       'suffix': '.png'},
      'primary': True}],
    'delivery': {'id': '365292',
     'url': 'https://www.grubhub.com/restaurant/subway-13726-4606-s-damen-ave-chicago/365292?affiliate=1131&utm_source=foursquare-affiliate-network&utm_medium=affiliate&utm_campaign=1131&utm_content=365292',
     'provider': {'name': 'grubhub',
      'icon': {'prefix': 'https://fastly.4sqi.net/img/general/cap/',
       'sizes': [40, 50],
       'name': '/delivery_provider_grubhub_20180129.png'}}},
    'referralId': 'v-1554961350',
    'hasPerk': False}]}}

In [29]:

venues = results['response']['venues']

# tranform venues into a dataframe
dataframe = json_normalize(venues)
dataframe.head()

,categories,delivery.id,delivery.provider.icon.name,delivery.provider.icon.prefix,delivery.provider.icon.sizes,delivery.provider.name,delivery.url,hasPerk,id,location.address,location.cc,location.city,location.country,location.distance,location.formattedAddress,location.labeledLatLngs,location.lat,location.lng,location.postalCode,location.state,name,referralId
0,"[{'id': '4bf58dd8d48988d1c5941735', 'name': 'S...",365292,/delivery_provider_grubhub_20180129.png,https://fastly.4sqi.net/img/general/cap/,"[40, 50]",grubhub,https://www.grubhub.com/restaurant/subway-1372...,False,4c378c483849c92809e8bdb1,4606 S Damen Ave,US,Chicago,United States,408,"[4606 S Damen Ave, Chicago, IL 60609, United S...","[{'label': 'display', 'lat': 41.80994293842322...",41.809943,-87.676834,60609,IL,Subway,v-1554961350

In [30]:

filtered_columns = ['name', 'categories'] + [col for col in dataframe.columns if col.startswith('location.')] + ['id']
dataframe_filtered = dataframe.loc[:, filtered_columns]


def get_category_type(row):
    try:
        categories_list = row['categories']
    except:
        categories_list = row['venue.categories']
        
    if len(categories_list) == 0:
        return None
    else:
        return categories_list[0]['name']


dataframe_filtered['categories'] = dataframe_filtered.apply(get_category_type, axis=1)


dataframe_filtered.columns = [column.split('.')[-1] for column in dataframe_filtered.columns]

dataframe_filtered

,name,categories,address,cc,city,country,distance,formattedAddress,labeledLatLngs,lat,lng,postalCode,state,id
0,Subway,Sandwich Place,4606 S Damen Ave,US,Chicago,United States,408,"[4606 S Damen Ave, Chicago, IL 60609, United S...","[{'label': 'display', 'lat': 41.80994293842322...",41.809943,-87.676834,60609,IL,4c378c483849c92809e8bdb1

In [31]:
dataframe_filtered.name

0    Subway
Name: name, dtype: object

In [139]:
address = '855 W North Ave ,Chicago,IL'



geolocator = Nominatim(user_agent="foursquare_agent")
location = geolocator.geocode(address)
latitude = location.latitude
longitude = location.longitude
print(latitude, longitude)

41.91061355 -87.6504481680296

In [140]:
search_query = 'Mexican'
radius = 500
print(search_query + ' .... OK!')

Mexican .... OK!

In [3]:
url = 'https://api.foursquare.com/v2/venues/search?client_id={}&client_secret={}&ll={},{}&v={}&query={}&radius={}&limit={}'.format(
    CLIENT_ID, 
    CLIENT_SECRET, 
    latitude, 
    longitude, 
    VERSION, 
    search_query, 
    radius,
    99)
url

In [142]:
results = requests.get(url).json()
results

{'meta': {'code': 200, 'requestId': '5cb0d3d71ed2196d94b031e1'},
 'response': {'venues': [{'id': '4ae0ca21f964a520838221e3',
    'name': "Uncle Julio's Hacienda",
    'location': {'address': '855 W North Ave',
     'crossStreet': 'at N Clybourn Ave',
     'lat': 41.9107157127916,
     'lng': -87.65045095940448,
     'labeledLatLngs': [{'label': 'display',
       'lat': 41.9107157127916,
       'lng': -87.65045095940448}],
     'distance': 11,
     'postalCode': '60642',
     'cc': 'US',
     'city': 'Chicago',
     'state': 'IL',
     'country': 'United States',
     'formattedAddress': ['855 W North Ave (at N Clybourn Ave)',
      'Chicago, IL 60642',
      'United States']},
    'categories': [{'id': '4bf58dd8d48988d1c1941735',
      'name': 'Mexican Restaurant',
      'pluralName': 'Mexican Restaurants',
      'shortName': 'Mexican',
      'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/mexican_',
       'suffix': '.png'},
      'primary': True}],
    'referralId': 'v-1555092439',
    'hasPerk': False}]}}

In [143]:
venues = results['response']['venues']

# tranform venues into a dataframe
dataframe = json_normalize(venues)
dataframe.head()

,categories,hasPerk,id,location.address,location.cc,location.city,location.country,location.crossStreet,location.distance,location.formattedAddress,location.labeledLatLngs,location.lat,location.lng,location.postalCode,location.state,name,referralId
0,"[{'id': '4bf58dd8d48988d1c1941735', 'name': 'M...",False,4ae0ca21f964a520838221e3,855 W North Ave,US,Chicago,United States,at N Clybourn Ave,11,"[855 W North Ave (at N Clybourn Ave), Chicago,...","[{'label': 'display', 'lat': 41.9107157127916,...",41.910716,-87.650451,60642,IL,Uncle Julio's Hacienda,v-1555092439

In [144]:
filtered_columns = ['name', 'categories'] + [col for col in dataframe.columns if col.startswith('location.')] + ['id']
dataframe_filtered = dataframe.loc[:, filtered_columns]

# function that extracts the category of the venue
def get_category_type(row):
    try:
        categories_list = row['categories']
    except:
        categories_list = row['venue.categories']
        
    if len(categories_list) == 0:
        return None
    else:
        return categories_list[0]['name']

# filter the category for each row
dataframe_filtered['categories'] = dataframe_filtered.apply(get_category_type, axis=1)


dataframe_filtered.columns = [column.split('.')[-1] for column in dataframe_filtered.columns]

dataframe_filtered

,name,categories,address,cc,city,country,crossStreet,distance,formattedAddress,labeledLatLngs,lat,lng,postalCode,state,id
0,Uncle Julio's Hacienda,Mexican Restaurant,855 W North Ave,US,Chicago,United States,at N Clybourn Ave,11,"[855 W North Ave (at N Clybourn Ave), Chicago,...","[{'label': 'display', 'lat': 41.9107157127916,...",41.910716,-87.650451,60642,IL,4ae0ca21f964a520838221e3

In [145]:
dataframe_filtered.name

0    Uncle Julio's Hacienda
Name: name, dtype: object

we can see From the above  it is clear that there are  more mexican restaranta,no Fast Food Restarants near School county so it's a good idea to start one

In [1]:
!jupyter nbextension enable --py --sys-prefix ipyleaflet

Enabling notebook extension jupyter-leaflet/extension...
      - Validating: ok

In [2]:
from ipyleaflet import Map
Map (center=[41.80972665, -87.671915249027],zoom=10)

Map(basemap={'url': 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', 'max_zoom': 19, 'attribution': 'Map …